### ISSUE TITLE
Pressing the 'Backspace' key while the NUI menu is open breaks everything

### ISSUE THREAD

**Issue by Adzeiros** [project-error/fivem-react-boilerplate-lua#58]
The issue is when you have the NUI menu open, or any NUI element open, and you press the 'backspace' key it will make the UI disappear and your curser will remain. You need to restart the script to fix it.

There is JSON error in the client console stating there is an issue with the JSON input. (line 1 of the HTML)

--EDIT--

Here is the error code if you need it:

`Uncaught (in promise) SyntaxError: Unexpected end of JSON input (@scriptname/web/build/index.html:1)`

**Comment by TasoOneAsia** [comment]
This is because, the blank boilerplate currently has no way of determining if the current UI element is open or not. Without editing it based on **your** context, this could happen. If you want some help determining how to do this, I would suggest coming to our Discord.

**Comment by Adzeiros** [comment]
Where can I find the Discord link?
