### ISSUE TITLE
Bug: Css hover elements with delay

### ISSUE THREAD

**Issue by FelipeLiraDev** [project-error/fivem-react-boilerplate-lua#69]
All elements with hover selector has a delay to disappear from screen

**To Reproduce**

1. Create any element with hover selector on css
2. Press esc or backspace

**Comment by FelipeLiraDev** [comment]
I changed the visibility provider method to close the ui and worked fine

**Comment by AntalCserhalmi** [comment]
Can you share your solution for this problem?
