### ISSUE TITLE
Question : Is an update needed to match the new React stuff ?

### ISSUE THREAD

**Issue by lexinor** [project-error/fivem-react-boilerplate-lua#79]
Hey !

I'm wanting to start my first React project in FiveM but I've some questions that came up while reading React's official documentation. It seems that some things have changed a lot lately in React and I would like to know if there would be needed to update this boilerplate to match the latest standards ?

Just wanna know if I can start learning without the hassle to update this later

Thanks in advance ! :)

**Comment by lexinor** [comment]
Like so : https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components/

**Comment by itschip** [comment]
Yep! We can update this repo to match the latest docs.

**Comment by lexinor** [comment]
> Yep! We can update this repo to match the latest docs.

Oh nice ! Thanks for your answer :)

**Comment by itschip** [comment]
Updated the packages and addes eslint as well.

**Comment by lexinor** [comment]
> Updated the packages and addes eslint as well.

Thanks !
